### ISSUE TITLE
Rename 'apis' property to 'x-apis'

### ISSUE THREAD

**Issue by janslow** [prestonvanloon/swagger-aggregator#3]
At the moment, files consumed by `swagger-aggregator` are schema invalid (according to [the spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#patterned-objects)). Therefore it's not possible to validate these files with a schema validator.

However, the spec does allow vendor extension properties which are prefixed by `x-`.

It would be useful if the `apis` property was renamed to `x-apis`, so that the source file could be schema valid.

**Comment by prestonvanloon** [comment]
Thanks for this. If you would like, please submit a pull request and I'll merge it. Otherwise, I'll submit one later this week.
